// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xndptitgalbtxmooblgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZHB0aXRnYWxidHhtb29ibGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTk3NDQsImV4cCI6MjA2NzIzNTc0NH0.enjcyM--gtvhRH_IEPmEOYVUykHb2LYMLecKTI57Fek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});